### PR TITLE
Manpage typo fixes

### PR DESCRIPTION
**Pull request by viiru-**
Fix a couple of typos in man pages.

### CODE REVIEW

**Comment by AlexanderS** [comment]
The man pages are automatically generated from the files in `doc/man`. So you may want to update these files. too.

**Comment by viiru-** [comment]
Huh. Didn't realise that they were both generated and shipped in the repository. I'll fix those as well.

**Comment by viiru-** [comment]
I pushed a new version with the source files fixed as well.

**Comment by AlexanderS** [comment]
Merged, thanks!

**Pull request merged**
