### PR TITLE
Fix SELinux support

### PR DESCRIPTION
**Pull request by gordonmessmer**

### CODE REVIEW

**Comment by solj** [comment]
:+1:

**Comment by gordonmessmer** [comment]
The test suite runs successfully in mock, in both CentOS 6 and CentOS 7 build roots.

**Comment by solj** [comment]
@stpierre @AlexanderS This looks good to me. Any thoughts?

**Comment by stpierre** [comment]
LGTM, too.

**Comment by solj** [comment]
Merged, thanks.

**Pull request merged**
