### PR TITLE
Lint/MergeFiles: Ignore binary files

### PR DESCRIPTION
**Pull request by AlexanderS**
Ignore files with binary content, because SequenceMatcher seems to have problems
and sometimes detect files with different content as identically.

### CODE REVIEW

**Comment by solj** [comment]
:+1:

**Comment by stpierre** [comment]
We have a different way to check if a string is binary here: https://github.com/Bcfg2/bcfg2/blob/maint/src%2Flib%2FBcfg2%2FClient%2FTools%2FPOSIX%2FFile.py#L20-L25 (We negate that check later: https://github.com/Bcfg2/bcfg2/blob/maint/src%2Flib%2FBcfg2%2FClient%2FTools%2FPOSIX%2FFile.py#L184)

Should we use the same approach in both places? Is one better than the other?

**Comment by AlexanderS** [comment]
Oh, the first part of the check is essentially the same, it checks if some bytes are outside the printable range in extended ascii. The check in POSIXFile also checks if the encoding is valid. So maybe we should move the check from POSIXFile into Utils or so and use this version.

**Comment by AlexanderS** [comment]
Done.

**Comment by stpierre** [comment]
LGTM.

**Comment by AlexanderS** [comment]
*grml* The test needs to be fixed.

**Comment by solj** [comment]
Merged, thanks!

**Pull request merged**
