### PR TITLE
Fix a variety of problems with YumHelper

### PR DESCRIPTION
**Pull request by gordonmessmer**
With the new options code, classes used as the parent argument to register_commands must not access the setup object in their init function, because that object hasn't been prepared yet. It's best, then, not to have an init function at all.

Various other changes were made to get bcfg2-yum-helper working again.

### CODE REVIEW

**Comment by gordonmessmer** [comment]
Ping

**Comment by solj** [comment]
I haven't used the YumHelper but this looks fine to me :+1:

**Comment by gordonmessmer** [comment]
Anyone else?

**Comment by solj** [comment]
@AlexanderS I assume you're not using the YumHelper either but does this look good to you?

**Comment by AlexanderS** [comment]
Yes, looks fine to me :+1:

**Comment by solj** [comment]
Merged, thanks!

**Pull request merged**
