### PR TITLE
Reporting: Remove invalid select_related

### LINKED ISSUE #356: Invalid field name(s) given in select_related
I see the following error when I view `/elements/bad` (and similar errors for `/elements/modified` and `/elements/extra`):

```
FieldError at /elements/bad

Invalid field name(s) given in select_related: 'target_perms', 'linkentry', 'current_perms'. Choices are: (none)

Request Method: 	GET
Request URL: 	http://.../elements/bad
Django Version: 	1.8.7
Exception Type: 	FieldError
Exception Value: 	

Invalid field name(s) given in select_related: 'target_perms', 'linkentry', 'current_perms'. Choices are: (none)

Exception Location: 	/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py in get_related_selections, line 754
Python Executable: 	/usr/bin/python
Python Version: 	2.7.11
```

```
Traceback:
File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/lib/python2.7/dist-packages/Bcfg2/Reporting/views.py" in _handle_timeview
  107.         return fn(request, **kwargs)
File "/usr/lib/python2.7/dist-packages/Bcfg2/Reporting/views.py" in config_item_list
  190.         if len(ldata) > 0:
File "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in __len__
  144.         self._fetch_all()
File "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in _fetch_all
  965.             self._result_cache = list(self.iterator())
File "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in iterator
  238.         results = compiler.execute_sql()
File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in execute_sql
  829.             sql, params = self.as_sql()
File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in as_sql
  378.             extra_select, order_by, group_by = self.pre_sql_setup()
File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in pre_sql_setup
  48.         self.setup_query()
File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in setup_query
  39.         self.select, self.klass_info, self.annotation_col_map = self.get_select()
File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in get_select
  206.             related_klass_infos = self.get_related_selections(select)
File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in get_related_selections
  754.                         ', '.join(_get_field_choices()) or '(none)',

Exception Type: FieldError at /elements/bad
Exception Value: Invalid field name(s) given in select_related: 'target_perms', 'linkentry', 'current_perms'. Choices are: (none)
```

My current workaround is to comment out the `select_related` call on [line 189 of src/lib/Bcfg2/Reporting/views.py](https://github.com/Bcfg2/bcfg2/blob/a24fd9e6966e70014ea776ac266350f902833b1e/src/lib/Bcfg2/Reporting/views.py#L189).

### PR DESCRIPTION
**Pull request by 0**
Fixes #356.

### CODE REVIEW

**Comment by AlexanderS** [comment]
I would think, that we should add an empty `select_related()`. In the current state, this code adds a sql query for _each_ entry with the properties.

**Comment by 0** [comment]
Put back the `select_related()` call.

**Comment by AlexanderS** [comment]
:+1:

**Comment by solj** [comment]
Merged, thanks!

**Pull request merged**
