### PR TITLE
Prevent lxml Element from being passed non-string data

### PR DESCRIPTION
**Pull request by gordonmessmer**

### CODE REVIEW

**Comment by stpierre** [comment]
LGTM.

**Comment by solj** [comment]
Is there a particular plugin that's setting the revision to a non-string character? This seems fine to me but it doesn't make sense to set it to anything other than a string initially afaict.

**Comment by gordonmessmer** [comment]
I suspect it's coming from the Hg plugin, but the core should probably be robust enough to correct simple type errors.

**Comment by solj** [comment]
Merged, thanks!

**Pull request merged**
