### PR TITLE
Keep trailing newlines in Jinja2 templates

### PR DESCRIPTION
**Pull request by gordonmessmer**
Jinja2 will, by default, trim a trailing newline from templates.  This might break some files, such as the iptables state file.

The "keep_trailing_newline" argument can be used to change that behavior.  The drawback is that the option was added in Jinja2 2.7, whereas RHEL 6 includes 2.2.

### CODE REVIEW

**Comment by stpierre** [comment]
If this is only available in newer Jinja2 libraries, I'd rather we only use it if it's supported. E.g., the naive approach would be something like:

    try:
        self.environment = self.__environment_cls__(loader=self.loader,
                                     keep_trailing_newline=True)
    except SomeException:
        self.environment = self.__environment_cls__(loader=self.loader)
        # and probably log a warning

**Comment by AlexanderS** [comment]
Maybe you want to rewrite the history to remove the wrong commit.

**Comment by gordonmessmer** [comment]
Yeah, I was in a rush on my way out of the office.

Try blocks are a little expensive, so I'll look at using distutils to check the Jinja2 version, and set a variable to control the keyword arg use.

**Comment by solj** [comment]
Closing as duplicate of #306

**Pull request closed without merging**
