### PR TITLE
testsuite: Require newer version of mock and change import

### PR DESCRIPTION
**Pull request by AlexanderS**
mock-1.1.0 was converted to a package and needs to be imported differently.

### CODE REVIEW

**Comment by solj** [comment]
:+1:

**Comment by stpierre** [comment]
Looks like mock's old CamelCase assertions have been removed, and we've got at least one of those still in the code, so that'll need to be fixed as well.

No RPM-based distribution has a new enough version of mock, so we'll need to comment out the %check section of the spec files.

**Comment by AlexanderS** [comment]
Oh maybe it's better to try/catch the two imports and do not require the newer version than. I will fix the CamelCase issue.

**Comment by solj** [comment]
Ah, even better. Now there's no need to comment out the RPM checks.

**Comment by solj** [comment]
Merged, thanks!

**Pull request merged**
