### PR TITLE
Fix date format

### PR DESCRIPTION
**Pull request by AlexanderS**
I wanted to customize the date and time formats used in the reporting web interface. This is the way to do it with django. I could now use something like ``django_settings = USE_L10N=true, LANGUAGE_CODE=de-DE`` and get correct German date formats.

### CODE REVIEW

**Comment by AlexanderS** [comment]
``Connection reset by peer`` in this one specific travis build should not be caused by this patch.

**Comment by stpierre** [comment]
This looks good (and the test failure indeed seems unrelated). Could you add an example of using the new option to the documentation, perhaps in ``doc/reports/dynamic.txt``? Thanks!

**Comment by solj** [comment]
Yep, restarted the build and it completed successfully. This looks good to me :+1: . Can you also mention this change in the 1.4.0pre2 release notes?

**Comment by AlexanderS** [comment]
If we merge 257eb0c17 into master, the format of this option will change. So lets keep this open until we merge again. I will then update this pull request.

**Comment by AlexanderS** [comment]
This is now on top of #295.

**Comment by solj** [comment]
Merged, thanks!

**Comment by AlexanderS** [comment]
Oh, just noticed, that I was missing the release notes again :(

**Pull request merged**
