### PR TITLE
DBSettings: Don't use django, if it's not available

### PR DESCRIPTION
**Pull request by AlexanderS**

### CODE REVIEW

**Comment by stpierre** [comment]
+1

**Comment by solj** [comment]
Isn't django required for DBSettings?

**Comment by stpierre** [comment]
The option parsing hooks are called regardless, though, so they should be no-ops if Django isn't available.

Aside: For 1.5 we should seriously look into making more things requirements. This is brittle and a little silly.

**Comment by solj** [comment]
Merged, thanks!

**Pull request merged**
